all: generate

generate:
	raco make tester.rkt
	raco make Milestone2/main.rkt
	raco make Milestone3/main.rkt
	raco make Milestone4/main.rkt
clean:
	rm -rvf Milestone2/compiled/ 
	rm -rvf Milestone3/compiled/ 
	rm -rvf Milestone4/compiled/ 

